feat: add html link component
ogcio/govie-ds pull request #184
Opened 2024-08-28 15:56 UTC by hamza14khan

- Addition of html link component and macro.
- Customisation options with `external`, `noUnderline`, and `noVisited` states.

![Screenshot 2024-08-28 at 16 54 57](https://github.com/user-attachments/assets/a0301f01-c2a3-4733-9ea0-0e38e0a0edf9)

2024-08-28 16:00 UTC, pregno reviewed
Could you add a simple usage example in `example/wagtail` and `example/nextjs`?

2024-08-29 16:21 UTC, BogdanDanilescu approved these changes

2024-08-30 16:26 UTC, pregno requested changes

2024-08-30 16:26 UTC, pregno commented on packages/html/ds/src/link/link.html
> +  {% macro getDarlClass(dark) %}
```suggestion
  {% macro getDarkClass(dark) %}
```

2024-08-30 16:26 UTC, pregno commented on packages/html/ds/src/link/link.html
> +      {{ getDarlClass(props.dark) | trim }}
```suggestion
      {{ getDarkClass(props.dark) | trim }}
```

2024-08-30 16:36 UTC, hamza14khan commented on packages/html/ds/src/link/link.html
> +  {% macro getDarlClass(dark) %}
Good catch!

2024-08-30 16:37 UTC, hamza14khan commented on packages/html/ds/src/link/link.html
> +      hover:gi-text-blue-800
Yes, spot on! Its duplicate. Updated ✅

2024-08-30 16:49 UTC, pregno approved these changes

2024-09-02 09:03 UTC, merged