feat: add react `Card` component
ogcio/govie-ds pull request #285
Opened 2024-10-11 16:41 UTC by hamza14khan

- Addition of react `Card` component (horizontal, vertical and icon).
- Update associated documentation.
- Documentation files prefix updated.

Testing on Storybook:
![Screenshot 2024-10-11 at 16 56 22](https://github.com/user-attachments/assets/58eb5993-6c2b-4069-956c-a7a89662753e)

Testing on Example application:
![Screenshot 2024-10-11 at 16 56 08](https://github.com/user-attachments/assets/47aef8e7-d365-4a5d-9750-efc92a2c0184)

2024-10-14 07:53 UTC, pregno requested changes
Nice work, just a minor change.

2024-10-14 07:53 UTC, pregno commented on packages/react/ds/src/card/card.tsx
> +          {href ? (
Move this ternary operator inside the `Heading`, something like:
```
<Heading as="h5" customClasses="!gi-mt-0 !gi-mb-0">
   {href ? <Link href={href}>{title}</Link> : title} 
</Heading>
```

2024-10-14 08:35 UTC, BogdanDanilescu commented
Minor lint issues
![image](https://github.com/user-attachments/assets/d5a7eec3-6c80-453b-a0cb-4569450a015f)

2024-10-14 14:45 UTC, hamza14khan commented on packages/react/ds/src/card/card.stories.tsx
> +// Default card example
Not at all. Removed 👍

2024-10-14 15:51 UTC, pregno approved these changes
Wait for Lexa review before merge

2024-10-15 07:37 UTC, BogdanDanilescu commented on packages/react/ds/src/card/card.tsx
> +  icon?: ReactElement;
can we do here `ReactElement<IconPropTypes>` ? it ensures we are passing the right props

2024-10-15 10:16 UTC, BogdanDanilescu approved these changes
LGTM

2024-10-15 10:30 UTC, merged